### ISSUE TITLE
npm en-dictionary page is out of date

### ISSUE THREAD

**Issue by psnider** [open-language/en-dictionary#23]
I found en-dictionary on npm at https://www.npmjs.com/package/en-dictionary

Unfortunately its documentation is out of date.  
The example code does not work in node, as it requires "./index" which is not in scope.  
Also, it took me awhile to find this repo, since there is no git reference on the npm page.

If this is the repo for that npm package, can you please update npm?
If this is not, do you know which repo is?

**Comment by sudhanshuraheja** [comment]
This has been updated @psnider, sorry about the confusion.
